# Generated by Django 5.1.1 on 2024-09-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_brand_address_brand_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="address_line_2",
        ),
    ]
