# Generated by Django 5.1.1 on 2024-09-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projectimages_brand_project_img'),
        ('main_app', '0016_remove_user_brand_user_brand_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
