# Generated by Django 5.1.1 on 2024-09-22 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('guide', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
