# Generated by Django 5.1.1 on 2024-09-20 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_community_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeowner",
            name="payment_status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.AddField(
            model_name="materialprovider",
            name="payment_status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="payment_status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.CreateModel(
            name="SupportTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
