# Generated by Django 5.1.1 on 2024-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_homeowner_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
