# Generated by Django 5.1.1 on 2024-09-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_community_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialprovider",
            name="user",
        ),
        migrations.RemoveField(
            model_name="serviceprovider",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="brand_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="firm_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="firm_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="intrest",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_doc",
            field=models.FileField(blank=True, null=True, upload_to="profile_docs/"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_gallery",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_gallery/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="user",
            name="project_img",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="HomeOwner",
        ),
        migrations.DeleteModel(
            name="MaterialProvider",
        ),
        migrations.DeleteModel(
            name="ServiceProvider",
        ),
    ]
