# Generated by Django 5.1.1 on 2024-09-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profilegallery_projectimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Home Owner', 'Home Owner'), ('Service Provider', 'Service Provider'), ('Material Provider', 'Material Provider'), ('Community User', 'Community User')], max_length=20),
        ),
    ]
