# Generated by Django 5.1.1 on 2024-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
