# Generated by Django 5.1.1 on 2024-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_user_project_img_remove_user_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brand',
        ),
        migrations.AddField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
