# Generated by Django 5.1.1 on 2024-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporttickets',
            name='user',
        ),
        migrations.AddField(
            model_name='supporttickets',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supporttickets',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporttickets',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
